### PR TITLE
Remove dependency on HCI

### PR DESCRIPTION
**Pull request by Sandorik00**

### CODE REVIEW

**Comment by ghost** [comment]
I specifically designed HCI to work without coding knowledge. HCI does not break anything.

**Comment by Sandorik00** [comment]
You really want force users download another separated lib just to avoid pretty clear `ig.merge` function?

**Comment by ghost** [comment]
It's one extra lib. And it is hardly a hassle to download.

**Comment by dmitmel** [comment]
@ac2pic 

> I specifically designed HCI to work without coding knowledge. HCI does not break anything.

Don't want to sound condescending, but I believe that HCI is redundant in the context of Autumn's Genesis.

1. It's not like @Hsifnus can't code or that you don't need programming knowledge to contribute to significant parts of Autumn's Genesis (outside of sprites and music).
2. I agree with @Sandorik00, the `ig.merge(ig.BGM_TRACK_LIST, { ... })` is pretty clear, and the merged object can be written as plain JSON inside the JS code, so you don't need particular programming knowledge outside of JSON to copy this snippet.
3. Consider where @Sandorik00 moved the track list which was previously injected by HCI. Take a look at the following code. @Hsifnus could have used `default-tracks.json` functionality of HCI for that, but the call `ig.merge(ig.BGM_DEFAULT_TRACKS, { ... })` is there, so I don't believe that removing HCI in favor of that will affect anything. _This is my main point._
4. An additional problem with HCI is that it doesn't support browsers ¯\\\_(ツ)\_/¯

> It's one extra lib. And it is hardly a hassle to download.

I would agree with this if Autumn's Genesis had 15-20 dependencies, but we are talking about removing a 5th or 6th dependency, which is significant enough to be removed in the context of ccmodding IMO.

**Comment by ghost** [comment]
You are right.

**Comment by dmitmel** [comment]
Also, I want to remind that removing HCI from Autumn's Genesis isn't about deprecating HCI entirely, it's about making so that popular mods (Arcane Labs and Autumn's Genesis) don't depend on it when we reach the CCLoader v3 release because HCI **needs** porting to be compatible with v3 (as I removed `activeMods`). This dependency of Arcane Labs has already been successfully removed and by removing it from Autumn's Genesis we no longer have popular mods depending on it.

**Pull request merged**
